language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
- gem install dpl
- dpl --provider=pypi --username=__token__ --password=$PYPI_TOKEN --verbose
