language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: AL6GruTlWUNue7pooPt0bsq66goI8tAOntJnz3GAcSWaz+Hfs7TGYpucYgcGBQZysQpa4pGQipKrjRdEmOUGjnpaiKptlXNgvUy4y86INdLNlNkk33oZvLzsLkcBAmJit8zkCQMmThdzp0XtI0CHnKs1M/JIfIcB3jiUnLiJeBNZYdUkF9HU4kVOr3EmXIeouqFlwkpqbAZfNgiQznCHGpHv2b4kKECzr+9sj4k7oei7qmvZSDqryeRhu3Pey1j+xDvdAO6yDlPMDaQ8lKgkTy1hG+wYmtlsd9isSimJ90oXvUpxTY2JYnmm8LRQ9RUsdJEFIWuFCm1nqAwYKilpZE5QE+TYHstMg2w0rR/EI0yDm5TM5e07OTfEDy1WyNYRBx/h2T2AilJSHwi0GDbdVZCyDKGMO8soMNuZVN55v+OZsDQBtcz8p0aWWL9ZRRlgagb6AwdDCa2APzcfOoKuBVAvMEgGlYM4GeHg742/zLCvFXYj5taHJqT+gJNhAPl4MVN4sV/LqlUHebHzMSGqm4tf9W/3wm9/o2nQhwDUlZ1SzfLW/mh9fNozVKoB0MPCu0/R4yhCvLA2Uz4rP68BSKSc5NE1in6WWG+1HlLpSOqdZ8uMsjgEyRFdcPEfDrJzIZH2Gw/RUMjr+yoeujK1duiimeY/CFpQsSjXY87v2z4=
