language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- if [ "$TRAVIS_PYTHON_VERSION" = "3.4" ]; then coveralls; fi
deploy:
  provider: pypi
  username: __token__
  password: $PYPI_TOKEN
  on:
    branch: master
    python: 3.4
    tags: true
