language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: shouryaps
  password:
    secure: oCMDS9jYZ0bb0QV9+tLOMrN5kcZk7Ee9MlvlbUnfd+PMGxYhc+9IeTiX2mKaglEAjIvXl1r0Rw+6wmHBbie1RIAJEGEbAQYoQRppZRi7gI07627y0ecBb28TpJsH6Nyg+1DZf53ZIzCwshotW6KZLDRXejPLW0E8kW+vNvkv9FB5fJMX0fVygPHGcPHxk+bFRGNvJEv41SGXKvdgLQpev5OWj8lOqAbLjPmB23j9Xm39wOAqzAUZ8Z7rr+zGo54MR4PCFXVyJF6AwUqbrzfHpZBbEFuSHodWtOI1UfuLpTnQ83V9lwoo5+Lwae3m7D+hDiiFJrqMoQykbkYgx+zTwQWGMThJn2v/K5HyhBOZnN7p6MqQznq47b6Q2yV+wrYQVUCSEom6o9ZZlIp0br7agPJx9U0fhZU38AADFbfiUUmvevkZaTXU95IcojdaOffQOR7axXQX3aQqGi0FPHVqX4utP+zhEgOrrW1FmrvJ4Hrc4G9bbSSrx4UWmSukm+2inXGxacq+P/0h1dnerhYreH/LH6koJ6BwsVHMzvoXZAPPPzs/gbnzuyWdQriZXKEx1p9NaHvCQYjXe2DTBJ54FV1wM2IQeXvwoIUOlRgD8xnq5yZg+5CZ1R+r8gfeDoXB2Fj2GTw7c0BA6RGSHBOEJGqmPmoyzhIN8DHLawAjqqw=
