language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: shouryaps
  password:
    secure: hrWP5dkURiw00NKEpnBZw8UpeFNj8Qt22N32ZDqZzFxI0gLaHqKw02WKyKylUm0RE+dlVVG522mP3pUzTv+BG1X0FxCD/FVh5nD5jkei5i4tiATofi/qaQc6kAeKYlSYRdOMqUowI3VGxeT/vnMWiGHTw2Yd35FeQwQ+UkOkjv+f0GYvhLNzxoe6HPMpqnCMvjSeiApkEBVlUKUKb8CBuK+QjV1Xql5vgOmQdHUKDxwY2nlrCXxE+DNBDwL4aMgVqniCWsH+5pxvG/jlMcCFViAkcEgY5Aq0xYbt7vK/CplsCa9bvEDxuXUrfdzw2ddxBWHZhMcBRuGU1qO1XkuQw65k0eupB2pMlNd9eehvBXvXOdrStgRcOxfwT60NVVrJrlo9mvYX3VQak/I/p4CAkO9ArwygcQbg7ffuytgQByjNsnCTsVIsuHhhNZXfmqPrA+e+8PO80T8rBAXtU8unKbCH29T8OrexQWqB0Vm0zTBgNc3og5v8wRBFwQMTyfuN4WrFTkWCDow8V8GuE/cy9jl5zEzo44Jy5GlTMxE96wEKDViL8l16taz29qSjyAKh5qC04S25z0jcIfxytEvoVWbG7ukIk1sd6k09YnYuSXll6A+mNabisZwpsvX4KEFy/oDpjU+FdlxePLGYJ/f5spxBTAE9tR6B+AicKzRSNAc=
