language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: xvy0iTH2wQpmC+s7JZAykiqL+5SK8vvTNIuOffzZTvzE7wqbpeFZFl0xygcABLwCN/GAc7fkc4Z2ZA9XlcAJLdQKLZNHTA3y0/FEEDM/AXmskoCInCat22dhfvjYZ0YgqViRE/2E/LYRom88GdTA1GA65/ETBhNbiuR0sWgQScs0mUsU5cSDo3q/teNVRidkSs0AGgnpmzaVH0bDWedyjUdg3ef19YeyOF8p3YXzj0wTXE60uGfAGuVLhR+/6K2K/02/sVQZ0amznMfVJHy9A12sxFtoHNwJ0mjpsmdZKjQ65XbQN/Cai5zpSLfXpqaQ5zn7en2E+5zXLMpr2yVsSsKbAPqL4I/VHFwJX8LHJsZkl4jFDKT1zD/HaKZMxOloAEsshsvsDD6Kc0iqwe9eYQg55D6s51BNSRbon7VTkUvRoPC7dVLAOl2iSLfj401yeFzlC+tmamZmkrREzl0RafAmVi9z0YiwnAZynhdGHY7Kg8+9VsFPqR9TavCd/WpvpQCpvEDQNF1kAirOAFB4Q9L7pfd5zzBoT0b9ggDJhSV6VHvdcVac1AxEDFHxg92DlF6o6vFgCst6YI6XVkEcvqDqH1THQcj1tvHloNxjyMj4W1orLdTIKLmgvyYdIqurY4pISF4v6vnqj4exfD4ciulY4+kqNryLn+VBXzUjgfI=
