language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: aQpb2ayFnmnWY7Mg54y6lylE6WkZ2qHqCEKz3UbfYcQVtQ7nuumuN/gqc2VrBGlDy07chySErnMMYb1YjIJzeeYuU0K3q8os3MEDYTqf7n+JnI2ICAtJuQkYGJeULykVEsXCL3dCZOAM6RrnVFk0bl2XR92gliZTXj8/w5W2jpSgjGIuk6YvgGVHueSHaz8zbB7skEVmTR/Ul9HUGr73CUARVNgnX7RPFuoJAXtFFCEMVvARGF1xIe96Otq6cPM465eJyznvjThrLjebomFF3c/qTKJwp7l85JH5slLz24ezg0b37M+QvqY2sicidPKiZIeAq9Fc1cntoJNtEQpX1uSndIw39PwCXxCvZjsT8bW828+o6y0wJV7xsdKtUJt4NuRh21p7Bl/IC72wcUNV3JOJ4nC905bN2QdVZDKBA+uYYBnl2lmGdOvDdsp7gvPFme/HUnEAA5HzH8nDVKi9fLuQxzJCwNJS6lvqBzYvI51KNt/MOdSj+DU4X6WmCwTWa22KLwPLHvjZi5t4GqTt0EsHxLU8xXTTC/5pxE8njpnV4Bf+I8IMF7UlWgpjkR+wFszs2bxwmEmehn0zM2pu7pmXYMUMqUmCJELq057U0pcM8e03hB4tjA+LxyiSx1drpzjg+VxezokmqGWIKI28fGYDTZv/qDMdREPcbS8VwoY=
