language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: shouryaps
  password:
    secure: QxpVUtU58qXbj21MCZGAGaK/4Z3nkmFOicoMFD90hhlJt109tHgyEW4aiAFP1EPujxK+YVYvmTUKyl94aYig5lWLAZ2RYsPv4x8hsPirXoVXccLj9ej7n+4f2Mvges5d5SejPfqeSOOFTNtVeG6L/9xNZVCgPBU50N1BGd/sVLsKdNpclwP+LJJbxhfucMxMmmfkfySDBAH+6CV8HhuZIK4FNfXfkn5BEKe6BRO27cal3R1ro5bwbGxNZH+C/DwiUEaTYZQh6NypyoXWGt9F0gNlaehGyVEJYJnD9+7IfyOylIxddHUg+pgvOrGKXdZDnPy0ppdRZnTcQBS//+G3vYR2LBj0/wZ4gJ/7As+OK0cNtSAItdvZHz6XkyHFp422R6yWjHKkvgrBxeiaUzm35rK5FOBBlq96fODwIjyjdr6J0odEhzdEOWBXMm9szqhvWuOJvhwjhAfOQnZeClRz9vUyauwv4/nhH6kQ+FNjp9lSodXu7Z+uKZKHYUtmK+5pVPk4GpOsvYC4+IT2NyrSk88mdzE2ehsob7gxv9UeMX2UlTlinwJFfM3TitkcK8xd553AkxbSb0dlp31wuqLivbnqeN9WR0OiVQfm3/ebkY327cmWw+Xi8SjjnJAajmzE0PZptYn00dCY/iIqxH+bAD1bLijd4KuiybIwXiNHNw0=
