language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: shouryaps
  password:
    secure: KPxBC4Qzf5GSboEVydNM9wQNwzgIFQMX3gYKilCS29h0oLuVplEP6CsNRxOJRgSDdr+vQXO2tl8d25Vi04qaDP4LSrcXBcQ27O88ChLnjEaOUp0pF+yAlRDWXOtVwYk8411EJQrwuKZde5/JyVhv+XMks+8/n5/GOTgXtZEGuf1MnxZaA5Y6GphO2ldAfaAQKSqxj4U5KQYxlKRBfxFFl6BmfD9mOQoQBwjkD/sjt5y7WxBrLdf9oXtssQyQCvtfMvWw+TBWaEBl72bZfYCxYTCad1jTuHZW98FXyS1WO9my+i0o8YHly+q2HBhuX0Odp8ObszHfUV/0pEP7F8DfaETeUrN7/WmO/04O5Ypuqb+EQtH0ZynGKg02E9n3kSmq6CzRXWHg56kfE/ZmkejBF1QXSaf8KdAVVQ08raxenENPILH1CTYZuSLZMmDGLGr/gWi5ORahqae9PuqqwwPg9JDfebcrJYX5HS/iiJZElaRoB014AJxVu1uPStczRs6Ghrh1GkgKNbLiHKKgTN1zXm1AhkCQH8XyNPHl/1dYZJtCV305KWSDYZEC0vXSQ+n40CYDlBnskHUBRwxL3wVWjKm3qDtfgefaN3AOqnGaEGIVXRrQMivFbKN1g+x/OsiopZcZQnmfvmlT4VMOpjA1q6zm5+pzXmpmRDq3HQYrZM4=
