language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
install:
- pip install requests
- pip install python-coveralls
script:
- coverage run --source=finbox_bankconnect tests.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: shouryaps
  password:
    secure: DF+ITxhQ6uHn58FzOxG/5hGN3rkgW2tl7+WOZTir+S/liQN87ZAO3nwQ8ypKd6ilSPLGS0Wu+iyEyAFJ5jyhyCdYq2Y2loYC2T9yWBb4t4lUX+p7AzBS3enfAwKemgi4kc7Hn57MXgx7CU3yvkM8tuPLddCfDG5tElkuso0SJ/dovNDpoicJvUaOTi9WiCTbLftmGgEWzUhrBdQWvpsQiC3ykNEUidQufXJBmM0Vwe0uX5KbCxvGwq3vSjSk3SjoxEJ1oLjxLQm7d2lBWn3h0ILOHDNQ8ISg4GFB+tRNnDKz1rNdzSVgenWbru1TkCbWQMWSSRnou6U7pBxuOWhyaz6FOyZS3jX5pSR8dmaxxbjZ1E1UtOLqIn47fHmtP1oME7QG4m6X18GbFr3CR8RFy7AKODVS1vPgCvoAo1Hw7f4xZBceryfkLhdsRovWXubFzNyPvzv2sBYqbcWGMWPUP+pE87aXfVTUqG7isURI4GYBPAx+rQ13DAdotQYF30TS4kG/s7IF4q/tqrERoBofL/tO5WEkshYewXJjeoqSnJXnD+CzezYAzXgSVF+x5qqt/EU8Xuh/BiLG68eZHEm1tF3eeetpJqAjG1PLl0fFxpcWITnMn5SBK8UdcC4NvxhKNcM+VKu1+TNyYLnH58EV7l3XUm894MrzrQAle9c4TVo=
